param(
    [ValidateSet("emulator", "usb")]
    [string]$Profile = "emulator",

    [int]$BackendPort = 4000,

    [int]$ExpoPort = 8081,

    [string]$AvdName = ""
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[HEMS] $Message" -ForegroundColor Cyan
}

function Test-CommandExists {
    param([string]$Command)
    $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

function Get-AdbDevices {
    if (-not (Test-CommandExists "adb")) {
        return @()
    }

    $raw = adb devices 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $raw) {
        return @()
    }

    return $raw |
        Select-Object -Skip 1 |
        Where-Object { $_ -match "\tdevice$" } |
        ForEach-Object { ($_ -split "\s+")[0] }
}

function Start-EmulatorIfNeeded {
    param([string]$RequestedAvdName)

    $devices = Get-AdbDevices
    $hasRunningEmulator = $devices | Where-Object { $_ -like "emulator-*" } | Select-Object -First 1
    if ($hasRunningEmulator) {
        Write-Step "Android emulator already running: $hasRunningEmulator"
        return
    }

    if (-not (Test-CommandExists "emulator")) {
        Write-Step "No running emulator detected and 'emulator' is not in PATH. Expo will try to open Android itself."
        return
    }

    $avd = $RequestedAvdName
    if ([string]::IsNullOrWhiteSpace($avd)) {
        $avds = emulator -list-avds 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $avds) {
            Write-Step "No Android Virtual Devices found. Expo will try to open Android itself."
            return
        }
        $avd = $avds | Select-Object -First 1
    }

    Write-Step "Starting Android emulator: $avd"
    Start-Process -FilePath "emulator" -ArgumentList @("-avd", $avd) | Out-Null

    if (Test-CommandExists "adb") {
        Write-Step "Waiting for emulator to boot enough for Expo to install/open the app..."
        adb wait-for-device | Out-Null
    }
}

function Enable-AdbReverse {
    param([int]$Port)

    if (-not (Test-CommandExists "adb")) {
        throw "The usb profile requires adb in PATH so the script can run 'adb reverse tcp:$Port tcp:$Port'."
    }

    $devices = Get-AdbDevices
    $physicalDevices = $devices | Where-Object { $_ -notlike "emulator-*" }

    if (-not $physicalDevices) {
        Write-Step "No physical USB Android device is currently listed by adb. Connect the phone and approve USB debugging if Expo cannot open it."
    }

    Write-Step "Configuring adb reverse for backend port $Port."
    adb reverse "tcp:$Port" "tcp:$Port" | Out-Null
}

$repoRoot = $PSScriptRoot
$backendDir = Join-Path $repoRoot "Backend"
$mobileDir = Join-Path $repoRoot "Apps\Mobile"
$mobileEnvPath = Join-Path $mobileDir ".env"

if (-not (Test-Path $backendDir)) {
    throw "Backend directory not found: $backendDir"
}

if (-not (Test-Path $mobileDir)) {
    throw "Mobile directory not found: $mobileDir"
}

if (-not (Test-CommandExists "npm")) {
    throw "npm is required but was not found in PATH."
}

$backendUrl = if ($Profile -eq "emulator") {
    "http://10.0.2.2:$BackendPort"
} else {
    "http://localhost:$BackendPort"
}

Write-Step "Using profile '$Profile' with mobile backend URL $backendUrl"

if ($Profile -eq "emulator") {
    Start-EmulatorIfNeeded -RequestedAvdName $AvdName
} else {
    Enable-AdbReverse -Port $BackendPort
}

$envContent = @(
    "# Generated by Start-HEMS.ps1. This file is intentionally ignored by Git.",
    "EXPO_PUBLIC_BACKEND_URL=$backendUrl",
    "EXPO_PUBLIC_TRANSPORT_MODE=http",
    "EXPO_PUBLIC_LIBRARY_SOURCE=http",
    "EXPO_PUBLIC_DEVICES_SOURCE=http"
) -join [Environment]::NewLine

Set-Content -Path $mobileEnvPath -Value $envContent -Encoding UTF8
Write-Step "Wrote mobile runtime config to $mobileEnvPath"

$backendCommand = @"
`$env:PORT='$BackendPort'
Set-Location '$backendDir'
npm run dev
"@

$frontendCommand = @"
`$env:EXPO_PUBLIC_BACKEND_URL='$backendUrl'
`$env:EXPO_PUBLIC_TRANSPORT_MODE='http'
`$env:EXPO_PUBLIC_LIBRARY_SOURCE='http'
`$env:EXPO_PUBLIC_DEVICES_SOURCE='http'
Set-Location '$mobileDir'
npx expo start --android --port $ExpoPort
"@

Write-Step "Starting backend in a new PowerShell window."
Start-Process -FilePath "powershell" -ArgumentList @("-NoExit", "-ExecutionPolicy", "Bypass", "-Command", $backendCommand) | Out-Null

Write-Step "Starting Expo frontend in a new PowerShell window."
Start-Process -FilePath "powershell" -ArgumentList @("-NoExit", "-ExecutionPolicy", "Bypass", "-Command", $frontendCommand) | Out-Null

Write-Host ""
Write-Host "Started HEMS with profile '$Profile'." -ForegroundColor Green
Write-Host "Backend:  http://localhost:$BackendPort"
Write-Host "Mobile:   $backendUrl"
Write-Host ""
Write-Host "Examples:"
Write-Host "  .\Start-HEMS.ps1 -Profile emulator"
Write-Host "  .\Start-HEMS.ps1 -Profile emulator -AvdName Pixel_8_API_35"
Write-Host "  .\Start-HEMS.ps1 -Profile usb"
